run:
  timeout: 10m

linters:
  disable:
    # deprecated but still enabled in the bugs preset
    - scopelint
  enable:
    - bodyclose
    - gofmt
    - goimports
    - gomodguard
    - gosec
    - misspell
    - revive
    - unconvert
    - unparam

linters-settings:
  misspell:
    locale: US
  gofmt:
    simplify: true
  gomodguard:
    blocked:
      modules:
        - io/ioutil:
            recommendations:
              - io
              - os
  unparam:
    check-exported: false
  goimports:
    local-prefixes: github.com/envoyproxy/go-control-plane
  exhaustive:
    default-signifies-exhaustive: true

issues:
